### ISSUE TITLE
Pull request template is slightly off base

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeXD/xd-awesome#21]
We should decide (and message clearly) if we want submissions to this repo in the form of issues or PRs. My vote is for PRs.

If we go with PRs, let's do the following:

1. Update the pull request template to include the info from the issue template
1. Reconsider what the issue template (and issues in general) on this repo are used for
1. Make sure it's clear to developers how to submit for inclusion

If we go with issues, a slight variation of the above is in order.

**Comment by kerrishotts** [comment]
So, the initial thinking with Issue + PR was that the discussion of whether or not something would be accepted could be taken on the issue, whereas the PR was only created _after_ approvals were given. The comments on the PR would then only be about the listing itself.

But I'm fine combining the two processes too.

**Comment by pklaschka** [comment]
Not meaning to pressure you, but this is now open for quite a while without any progress. Is this still being "worked on" (i.e., getting discussed or something like this)? Otherwise, if it'll stay the way it currently is, I'd suggest closing the issue 😉 (since folks should be encouraged to suggest repo's, an issue that's open for a long time without any progress isn't good for the repo's "reputation")...

**Comment by dkstevekwak** [comment]
My vote here is to go straight to PR as well. Since we will be reviewing the PRs anyways, removing an extra review step would make this process more efficient. Since @kerrishotts mentioned she'd be fine with combining the two processes, I think we should move to the new, streamlined process. I will work on this.

Issues will be used to raise issues of the existing listings (for example, listing no longer working or having significant bugs)

**Comment by ashryanbeats** [comment]
Thanks Steve! Sounds like a plan. Let's make sure it's clear in:

- Issue template
- PR template
- The "Contributing" section of the readme

**Comment by pklaschka** [comment]
@dkstevekwak The "Contributing" section of the README.md still has wrong instructions about contribution (cf. https://github.com/AdobeXD/xd-awesome#contributing), I'll, therefore, reopen the issue.

**Comment by dkstevekwak** [comment]
@pklaschka thanks for pointing that out. Addressed - 7acd037506ce0e898dafeeff33ccad79ece16908
